version: '3'
services:
    mongodb:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - ../apps/mongo-data:/data/db
        env_file:
            - ../apps/enviroments/mongo.env
        networks:
            - node-next
    uap-research:
        #Our container app name
        image: uapvid
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - ../apps/enviroments/uap-vid.env
        ports:
            - '80:3000'
        networks:
            - node-next
networks:
    node-next:
        driver: bridge
