version: '3'
services:
    mongodb:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - ~/apps/mongo-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        networks:
            - uap-vid-network
    uap-research:
        #Our container app name
        image: uapvid:latest
        build:
            context: . #Compose will use this context to find a Dockerfile
            dockerfile: ./Dockerfile #Compose will use this Dockerfile to build the image
        ports:
            - '80:3000'
        networks:
            - uap-vid-network
networks:
    uap-vid-network:
        driver: bridge
