version: '3'
services:
    mongodb:
        image: mongo
        volumes:
            - ../apps/mongo-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        networks:
            - node-next
    uap-research:
        #Our container app name
        image: uapvid
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - ../enviroments/uap-vid.env
        networks:
            - node-next
            - exposed-services
networks:
    node-next:
    exposed-services:
        external: true
