version: '3'
services:
  web-socket:
    image: uapsocket
    restart: never
    ports:
      - '8000:3001'
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - node-next

networks:
  node-next:
  exposed-services:
    external: true
