version: "3"
services:
  web-socket:
    image: uapsocket
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - node-next

networks:
  node-next:
  exposed-services:
    external: true