import { MongoClient } from 'mongodb'
import { ObjectId } from 'mongodb'
import 'dotenv/config'

const uri = process.env.MONGO_URI
const client = new MongoClient(uri)
const careers_and_courses = [
  {
    career: 'ACA - Adventist Colleges Abroad',
    assignment: [
      'RELH/SPAN 310 Contemporary Religious Outlook',
      'RELH/SPAN 313 The Adventist Professional',
      'SPAN 232 Phonetics',
      'SPAN 240 Orthography',
      'SPAN 251 Intermediate Spanish Grammar',
      'SPAN 252 Intermediate Spanish Grammar',
      'SPAN 253 Intermediate Spanish Grammar',
      'SPAN 261 Intermediate Spanish Composition',
      'SPAN 262 Intermediate Spanish Composition',
      'SPAN 263 Intermediate Spanish Composition',
      'SPAN 271 Intermediate Spanish Conversation',
      'SPAN 272 Intermediate Spanish Conversation',
      'SPAN 273 Intermediate Spanish Conversation',
      'SPAN 293 Language Through Drama',
      'SPAN 301 Folklore of Argentina',
      'SPAN 302 Folklore of Argentina',
      'SPAN 303 Folklore of Argentina',
      'SPAN 326 Translation and Interpretation',
      'SPAN 327 Translation and Interpretation',
      'SPAN 332 Latin American Literature',
      'SPAN 333 Latin American Literature',
      'SPAN 351 Advanced Spanish Grammar I',
      'SPAN 352 Advanced Spanish Grammar I',
      'SPAN 353 Advanced Spanish Grammar I',
      'SPAN 361 Advanced Spanish Composition I',
      'SPAN 362 Advanced Spanish Composition I',
      'SPAN 363 Advanced Spanish Composition I',
      'SPAN 371 Advanced Spanish Conversation I',
      'SPAN 372 Advanced Spanish Conversation I',
      'SPAN 373 Advanced Spanish Conversation I',
      'SPAN 381 Current Events in South America',
      'SPAN 382 Current Events in South America',
      'SPAN 422 Translation and Interpretation',
      'SPAN 423 Translation and Interpretation',
      'SPAN 451 Advanced Spanish Grammar II',
      'SPAN 452 Advanced Spanish Grammar II',
      'SPAN 453 Advanced Spanish Grammar II',
      'SPAN 461 Advanced Spanish Composition II',
      'SPAN 462 Advanced Spanish Composition II',
      'SPAN 463 Advanced Spanish Composition II',
      'SPAN 471 Advanced Spanish Conversation II',
      'SPAN 472 Advanced Spanish Conversation II',
      'SPAN 473 Advanced Spanish Conversation II',
      'SPAN/GEOG 205 Geography of Latin America',
      'SPAN/GEOG 306 Geography of Latin America',
      'SPAN/HIST 345 History of Argentina',
      'SPAN/HIST 346 History of  Argentina',
    ],
  },
  {
    career: 'Doctorado en Teología',
    assignment: [
      'Administración de iglesias y distritos pastorales',
      'Arameo bíblico',
      'Arqueología de Israel',
      'Capacitación de laicos para el servicio misionero',
      'Comunicación evangelizadora',
      'Crítica textual aplicada al AT',
      'Crítica textual aplicada al NT',
      'Estrategias del crecimiento eclesiástico',
      'Ética pastoral',
      'Evangelización por medio de la salud',
      'Exégesis avanzada veterotestamentaria',
      'Griego de la Septuaginta',
      'Historia del ministerio pastoral',
      'Historia del pensamiento misionológico',
      'Iglesia y sociedad',
      'Liderazgo en las organizaciones eclesiásticas',
      'Los dones y ministerios de la iglesia',
      'Matrimonio y familia',
      'Métodos avanzados de investigación',
      'Métodos de evangelización',
      'Métodos de exégesis del NT',
      'Métodos en Teología veterotestamentaria',
      'Métodos para establecer iglesias',
      'Misión urbana',
      'Morfosintaxis hebrea',
      'Orientación pastoral',
      'Pedagogía universitaria',
      'Religión, Derecho y Estado',
      'Seminario avanzado en Teología del NT',
      'Seminario en arqueología del Antiguo Cercano Oriente',
      'Seminario en arqueología del NT',
      'Seminario en culto y adoración',
      'Seminario en Eclesiología neotestamentaria',
      'Seminario en ética bíblica',
      'Seminario en exégesis del Apocalipsis',
      'Seminario en exégesis de las epístolas generales',
      'Seminario en exégesis de las epístolas paulinas',
      'Seminario en exégesis de los evangelios',
      'Seminario en exégesis del Pentateuco',
      'Seminario en exégesis de textos apocalípticos del AT',
      'Seminario en exégesis de textos históricos del AT',
      'Seminario en exégesis de textos poéticos y sapienciales del AT',
      'Seminario en exégesis de textos proféticos del AT',
      'Seminario en Filosofía contemporánea',
      'Seminario en la doctrina del santuario',
      'Seminario en literatura clásica judía',
      'Seminario en métodos de Teología sistemática',
      'Seminario en movimientos religiosos del siglo XIX',
      'Seminario en problemáticas del NT',
      'Seminario en resolución de conflictos',
      'Seminario en Soteriología contemporánea',
      'Seminario en tendencias escatológicas actuales',
      'Seminario en Teología de la inspiración del texto bíblico',
      'Seminario en Teología de las epístolas paulinas',
      'Seminario en Teología de libros históricos y proféticos',
      'Seminario en Teología de los escritos juaninos',
      'Seminario en Teología de los Evangelios sinópticos',
      'Seminario en Teología del Pentateuco',
      'Seminario en Teología histórica de la Reforma y Contrarreforma',
      'Seminario en Teología posmoderna',
      'Sintaxis y semántica avanzada del griego bíblico I',
      'Sintaxis y semántica avanzada del griego bíblico II',
      'Sociología latinoamericana y misión',
      'Taller de actualización bibliográfica en adoración y contextualización',
      'Taller de actualización bibliográfica en Antropología teológica contemporánea',
      'Taller de actualización bibliográfica en asuntos contemporáneos de Cristología',
      'Taller de actualización bibliográfica en asuntos  contemporáneos de la doctrina de Dios',
      'Taller de actualización bibliográfica en doctrina de la revelación',
      'Taller de actualización bibliográfica en doctrina del Espíritu Santo',
      'Taller de actualización bibliográfica en eclesiologías contemporáneas',
      'Taller de actualización bibliográfica en el mundo grecorromano',
      'Taller de actualización bibliográfica en el período intertestamentario',
      'Taller de actualización bibliográfica en éticas medievales y modernas',
      'Taller de actualización bibliográfica en historia de Israel y del Antiguo Cercano Oriente',
      'Taller de actualización bibliográfica en historia de la interpretación del NT',
      'Taller de actualización bibliográfica en historiografía del Antiguo Cercano Oriente',
      'Taller de actualización bibliográfica en judaísmo intertestamentario y del siglo I',
      'Taller de actualización bibliográfica en la formación del canon del NT',
      'Taller de actualización bibliográfica en la Septuaginta',
      'Taller de actualización bibliográfica en la Septuaginta',
      'Taller de actualización bibliográfica en métodos de evangelización posmodernos',
      'Taller de actualización bibliográfica en relación teológica entre AT y NT',
      'Taller de actualización bibliográfica en Soteriología  apocalíptica contemporánea',
      'Taller de actualización bibliográfica en textos sagrados de grandes religiones contemporáneas',
      'Taller de investigación avanzada I',
      'Taller de investigación avanzada II',
      'Teología de la misión',
      'Teología y ministerio de la adoración',
      'Teología y práctica de la predicación',
      'Tesis doctoral',
    ],
  },
  {
    career: 'Especialización en cardiología',
    assignment: [
      'Anatomía, fisiología y semiología cardiovascular',
      'Antropología médica y cosmovisión bíblico cristiana',
      'Bioética',
      'Caradiología pediátrica',
      'Cardiología Clínica',
      'Clínica Médica',
      'Electrocardiografía clínica',
      'Electrofisiología y arritmias',
      'Estilo de vida y salud',
      'Hemodinamia',
      'Inglés Médico',
      'Medicina legal',
      'Metodología del trabajo científico',
      'Métodos diagnósticos en cardiología (parte I)',
      'Métodos diagnósticos en cardiología (parte II)',
      'Recuperación cardiovascular',
      'Rotación electiva',
      'Rotación por cardiología clínica',
      'Rotación por cardiología pediátrica',
      'Rotación por clínica médica',
      'Rotación por consultorio de cardiología',
      'Rotación por electrofisiología y arritmias',
      'Rotación por hemodinamia',
      'Rotación por métodos diagnósticos en cardiología (parte I)',
      'Rotación por métodos diagnósticos en cardiología (parte II)',
      'Rotación por recuperación cardiovascular',
      'Rotación por urgencias y emergencias (parte I)',
      'Rotación por urgencias y emergencias (parte II)',
      'Rotación por urgencias y emergencias (parte III)',
      'Rotación por urgencias y emergencias (parte IV)',
      'Tutoría de trabajo final integrador',
      'Urgencias y emergencias cardiológicas',
    ],
  },
  {
    career: 'Maestría en Administración',
    assignment: [
      'Administración de organizaciones eclesiásticas',
      'Comunicación efectiva y resolución de conflictos',
      'Contabilidad gerencial y control de gestión',
      'Cultura y contexto organizacional',
      'Dirección estratégica',
      'Economía para la toma de decisiones',
      'Empresas de familia',
      'Etica, servicio y sociedad',
      'Finanzas de la empresa',
      'Gestión de la diversidad religiosa en el ambiente organizacional',
      'Gestión de la innovación',
      'Gestión de las operaciones y calidad',
      'Gestión del talento humano',
      'Gestión de organizaciones sin fines de lucro',
      'Liderazgo y trabajo en equipo',
      'Marketing',
      'Prácticas',
      'Responsabilidad social',
      'Simulación de negocios y toma de decisiones',
      'Taller de Trabajo Final',
      'Tecnología y competitividad',
      'Trabajo Final',
    ],
  },
  {
    career: 'Maestría en Teología',
    assignment: [
      'Administración y planificación pastoral (Area ET-P)',
      'Capacitación de adultos para la misión (Area ET-P)',
      'Conducción y gestión eclesiástica (Area ET-P)',
      'Crecimiento eclesiástico (Area ET-P)',
      'Didáctica de la educación religiosa',
      'Hebreos',
      'Hermenéutica bíblica',
      'Historia de Israel (Area EB)',
      'Historia del desarrollo doctrinal adventista',
      'Introducción a la Teología de la Liberación (Area ET-P)',
      'Jesús en la actualidad teológica',
      'Metodología del trabajo de investigación',
      'Misión eclesiástica (Area ET-P)',
      'Morfosintaxis intermedia del griego neotestamentario (Area EB)',
      'Organización de servicios solidarios y comunitarios (Area ET-P)',
      'Orientación pastoral (Area ET-P)',
      'Pensamiento bíblico judeo-cristiano',
      'Problemática contemporánea de la teología adventista',
      'Problemáticas en exégesis del AT (Area EB)',
      'Problemáticas en exégesis del NT (Area EB)',
      'Profetas menores (Area EB)',
      'Profundización en Antropología (Area ET-P)',
      'Profundización en Cristología (Area ET-P)',
      'Profundización en doctrina de Dios (Area ET-P)',
      'Profundización en doctrina de la Escritura',
      'Profundización en Eclesiología (Area ET-P)',
      'Profundización en Escatología (Area ET-P)',
      'Profundización en Ética cristiana (Area ET-P)',
      'Profundización en Pneumatología (Area ET-P)',
      'Profundización en Soteriología (Area ET-P)',
      'Salud integral y evangelización (Area ET-P)',
      'Seminario-taller en exégesis en el AT (Area EB)',
      'Seminario-taller en exégesis en el NT (Area EB)',
      'Seminario-taller en historia de la teología cristiana (Area ET-P)',
      'Seminario-taller en manifestaciones religiosas contemporáneas',
      'Seminario-taller en predicación bíblica',
      'Seminario-taller en teología del AT',
      'Seminario-taller en teología del NT',
      'Sintaxis intermedia del hebreo bíblico (Area EB)',
      'Taller de investigación I',
      'Taller de investigación II',
      'Taller de investigación III',
      'Taller de recursos informáticos aplicados a los estudios bíblicos',
      'Teólogos latinoamericanos contemporáneos',
    ],
  },
  {
    career: 'Castellano Lengua Extranjera - Alumnos de Angola',
    assignment: [
      'Composición',
      'Conversación y vocabulario',
      'Gramática y uso de la lengua',
      'Lectura comprensiva',
      'Ortografía',
    ],
  },
  {
    career: 'Castellano Lengua Extranjera - Lenguas Distantes',
    assignment: [
      'Composición',
      'Conversación y vocabulario',
      'Gramática y uso de la lengua',
      'Lectura comprensiva intensiva',
      'Ortografía',
    ],
  },
  {
    career: 'Castellano Lengua Extranjera - Lenguas Próximas',
    assignment: ['Apoyo de castellano (p/Sudam.)'],
  },
  {
    career: 'CRECON',
    assignment: [
      'Biblia',
      'Biología',
      'Comunicación y comprensión lectora',
      'Física',
      'Química',
    ],
  },
  {
    career: 'Enfermería',
    assignment: [
      'Anatomía y fisiología humana aplicada a la enfermería',
      'Antropología',
      'Aspectos psicosociales y salud en el ciclo vital',
      'Biofísica y bioquímica aplicada a la enfermería',
      'Comunicación oral y escrita',
      'Cosmovisión bíblica cristiana',

      'Educación física especial',
      'Enfermería básica',
      'Enfermería comunitaria I',
      'Enfermería del adulto y anciano',
      'Enfermería del niño y del adolescente',
      'Enfermería en salud mental',
      'Enfermería materno infantil',
      'Epidemiología I',
      'Epidemiología II',
      'Etica, deontología profesional y legislación en enfermería',
      'Expo Salud',
      'Farmacología I',
      'Farmacología II',
      'Farmacología III',
      'Filosofía aplicada a la enfermería I',
      'Fisioterapia natural',
      'Fundamentos del cristianismo',
      'Gestión de los servicios de enfermería hospitalarios y comunitarios I',
      'Gestión integral del riesgo civil',
      'Inglés aplicado a la enfermería',
      'Interpretación bliblica de la historia',
      'Investigación en enfermería I',
      'Microbiología y parasitología aplicada a la enfermería',
      'Nutrición y dietoterapia',
      'Prácticas integradas I',
      'Psicología',
      'Salud y autocuidado profesional',
      'Sociología I',
      'Taller de intervención en crisis',
      'Taller de proyectos',

      'Anatomía y fisiología humana aplicada a la enfermería',
      'Antropología',
      'Aspectos psicosociales y salud en el ciclo vital',
      'Biofísica y bioquímica aplicada a la enfermería',
      'Ciencia y fe',
      'Comunicación oral y escrita',
      'Cosmovisión bíblica cristiana',

      'Educación en enfermería',
      'Educación física especial',
      'Enfermería básica',
      'Enfermería comunitaria I',
      'Enfermería comunitaria II',
      'Enfermería del adulto y anciano',
      'Enfermería del niño y del adolescente',
      'Enfermería del paciente en estado crítico',
      'Enfermería en salud mental',
      'Enfermería materno infantil',
      'Epidemiología I',
      'Epidemiología II',
      'Etica, deontología profesional y legislación en enfermería',
      'Etica y desarrollo profesional',
      'Expo Salud',
      'Farmacología I',
      'Farmacología II',
      'Farmacología III',
      'Filosofía aplicada a la enfermería I',
      'Filosofía aplicada a la enfermería II',
      'Fisioterapia natural',
      'Fundamentos del cristianismo',
      'Gestión de los servicios de enfermería hospitalarios y comunitarios I',
      'Gestión de los servicios de enfermería hospitalarios y comunitarios II',
      'Gestión integral del riesgo civil',
      'Inglés aplicado a la enfermería',
      'Interpretación bliblica de la historia',
      'Investigación en enfermería I',
      'Investigación en enfermería II',
      'Microbiología y parasitología aplicada a la enfermería',
      'Movimientos religiosos contemporáneos',
      'Nutrición y dietoterapia',
      'Prácticas integradas I',
      'Prácticas integradas II',
      'Psicología',
      'Salud y autocuidado profesional',
      'Sociología I',
      'Sociología II',
      'Taller de intervención en crisis',
      'Taller de investigación en enfermería',
      'Taller de proyectos',
    ],
  },
  {
    career: 'Kinesiología',
    assignment: [
      'Administración de servicios de salud',
      'Anatomía I',
      'Anatomía II',
      'Antropología cristiana',
      'Biomecánica I',
      'Biomecánica II',
      'Ciencia y fe',
      'Cosmovisión bíblica cristiana',

      'Didáctica aplicada a la kinesiología',
      'Educación para la familia',
      'Educación social y sanitario-preventiva',
      'Ergonometría y posturología',
      'Estadística aplicada',
      'Etica y deontología',
      'Expo Salud',
      'Farmacología',
      'Filosofía de la educación cristiana',
      'Física biomédica',
      'Fisiología I',
      'Fisiología II',
      'Fisioterapia I',
      'Fisioterapia II',
      'Fisioterapia natural',
      'Fundamentos del cristianismo',
      'Histoembriología',
      'Inglés I',
      'Inglés II',
      'Interpretación bíblica de la historia',
      'Kinefilaxia',
      'Kinesiología del deporte',
      'Kinesiología legal y laboral',
      'Metodología del trabajo científico',
      'Pasantías kinésicas',
      'Prácticas en kinefisiatría cardiorrespiratoria',
      'Prácticas en kinefisiatría geriátrica',
      'Prácticas en kinefisiatría neurológica',
      'Prácticas en kinefisiatría pediátrica',
      'Prácticas hospitalarias I',
      'Prácticas hospitalarias II',
      'Principios de vida saludable',
      'Procesamiento electrónico de datos',
      'Prótesis y ortesis',
      'Psicología de la relación kinesiólogo-paciente',
      'Psicología evolutiva',
      'Psicomotricidad I',
      'Psicomotricidad II',
      'Semiopatología médico-kinésica I',
      'Semiopatología médico-kinésica II',
      'Semiopatología quirúrgica I',
      'Semiopatología quirúrgica II',
      'Taller 1',
      'Taller 2',
      'Taller 3',
      'Técnicas kinésicas I',
      'Técnicas kinésicas II',
      'Técnicas kinésicas III',
      'Tesis de licenciatura',
    ],
  },
  {
    career: 'Medicina',
    assignment: [
      'Administración en salud',
      'Administración en salud',
      'Anatomía',
      'Antropología teológica',
      'Asistencia espiritual del paciente',
      'Bioética',
      'Biología',
      'Ciencia y religión',
      'Clínica médica I',
      'Clínica médica II',
      'Clínica psiquiátrica',
      'Clínica quirúrgica I',
      'Clínica quirúrgica II',
      'Dermatología',
      'Diagnóstico por imágenes',
      'Educación para la salud',
      'Emergentología',
      'Enfermedades infecciosas',
      'Escatología bíblica',
      'Expo Salud',
      'Farmacología',
      'Física biológica',
      'Fisiología',
      'Gerontología',
      'Gerontología',
      'Ginecología',
      'Guardias Médicas',
      'Histología y embriología',
      'Historia de la medicina',
      'Historia del cristianismo',
      'Hogar y familia',
      'Hogar y familia',
      'Inglés médico',
      'Internado rotatorio de pregrado',
      'Introducción a la práctica final obligatoria',
      'Introducción al servicio solidario',
      'Introducción general a la Biblia',
      'Medicina legal',
      'Medicina preventiva',
      'Medicina social',
      'Metodología del trabajo científico',
      'Microbiología',
      'Neurología',
      'Nutrición',
      'Observaciones y prácticas generales I',
      'Observaciones y prácticas generales II',
      'Observaciones y prácticas generales III',
      'Obstetricia',
      'Oftalmología',
      'Oncología',
      'Otorrinolaringología',
      'Parasitología y micología',
      'Patología',
      'Pediatría',
      'Portugués',
      'Portugués',
      'Práctica Profesional Intensiva de Pregrado - Area Salud Mental',
      'Práctica Profesional Intensiva de Pregrado - Area Urgencias y Emergencias',
      'Principios de salud mental',
      'Psicología de la conducta',
      'Psicología de la relación médico paciente',
      'Química biológica',
      'Reforma pro salud',
      'Religiones comparadas',
      'Salud pública',
      'Semiología',
      'Servicio comunitario de pregrado',
      'Soteriología',
      'Teología de la salud',
      'Toxicología',
      'Traumatología y ortopedia',
      'Urología',
    ],
  },
  {
    career: 'Nutrición',
    assignment: [
      'Administración de servicios de salud',
      'Alimentación institucional',
      'Anatomía y fisiología humana I',
      'Anatomía y fisiología humana II',
      'Antropología cristiana',
      'Bromatología y tecnología alimentaria',
      'Ciencia y fe',
      'Cosmovisión bíblica cristiana',

      'Desarrollo socioeconómico y abasto de alimentos',
      'Didáctica aplicada a la nutrición',
      'Economía familiar',
      'Educación para la familia',
      'Educación para la salud',
      'Epidemiología general y nutricional',
      'Estadística aplicada',
      'Etica y deontología profesional',
      'Evaluación en nutrición',
      'Expo Salud',
      'Filosofía de la educación cristiana',
      'Fisiopatología y dietoterapia del niño',
      'Fisiopatología y dietoterapia I',
      'Fisiopatología y dietoterapia II',
      'Fundamentos de la alimentación',
      'Fundamentos del cristianismo',
      'Informática aplicada a la nutrición I',
      'Inglés I',
      'Inglés II',
      'Interpretación bíblica de la historia',
      'Metodología del trabajo científico',
      'Microbiología',
      'Nutrición en salud pública',
      'Nutrición materno-infantil',
      'Nutrición y alimentación humana I',
      'Nutrición y alimentación humana II',
      'Parasitología',
      'Práctica en dietética institucional II',
      'Práctica en salud pública I',
      'Principios de vida saludable',
      'Procesamiento electrónico de datos',
      'Programación en nutrición',
      'Psicología aplicada',
      'Psicología de la educación',
      'Psicosociología de la alimentación',
      'Química biológica',
      'Relaciones humanas y desarrollo de la comunidad',
      'Salud pública',
      'Saneamiento ambiental',
      'Técnica dietética y práctica coquinaria I',
      'Técnica dietética y práctica coquinaria II',
      'Técnica dietoterápica I',
      'Técnica dietoterápica II',
      'Tesis de licenciatura en nutrición',
      'Tesis de licenciatura en nutrición II',

      'Administración de servicios de salud',
      'Anatomía y fisiología humana I',
      'Anatomía y fisiología humana II',
      'Antropología cristiana',
      'Bromatología y tecnología alimentaria',
      'Cosmovisión bíblica cristiana',

      'Desarrollo socioeconómico y abasto de alimentos',
      'Economía familiar',
      'Educación para la familia',
      'Educación para la salud',
      'Epidemiología general y nutricional',
      'Estadística aplicada',
      'Etica y deontología profesional',
      'Expo Salud',
      'Fisiopatología y dietoterapia del niño',
      'Fisiopatología y dietoterapia I',
      'Fisiopatología y dietoterapia II',
      'Fundamentos de la alimentación',
      'Fundamentos del cristianismo',
      'Inglés I',
      'Inglés II',
      'Interpretación bíblica de la historia',
      'Metodología del trabajo científico',
      'Microbiología',
      'Nutrición materno-infantil',
      'Nutrición y alimentación humana I',
      'Nutrición y alimentación humana II',
      'Parasitología',
      'Principios de vida saludable',
      'Procesamiento electrónico de datos',
      'Química biológica',
      'Salud pública',
      'Saneamiento ambiental',
      'Técnica dietética y práctica coquinaria I',
      'Técnica dietética y práctica coquinaria II',
      'Técnica dietoterápica I',
      'Técnica dietoterápica II',
    ],
  },
  {
    career: 'Odontología',
    assignment: [
      'Anatomía general',
      'Anatomía odontológica específica',
      'Anatomía patológica',
      'Antropología',
      'Aspectos psicosociales y salud en el ciclo vital',
      'Biología',
      'Bioquímica básica y aplicada a la odontología',
      'Ciclo de introducción y nivelación para la carrera de Odontología',
      'Cirugía y traumatología bucomaxilofacial I',
      'Cirugía y traumatología bucomaxilofacial II',
      'Cirugía y traumatología bucomaxilofacial III',
      'Clínica de operatoria dental',
      'Clínica de prótesis completa',
      'Clínica de prótesis fija',
      'Clínica de prótesis integrada',
      'Clínica de prótesis parcial removible',
      'Clínica estomatológica',
      'Cosmovisión bíblico cristiana',

      'Diagnóstico por imágenes',
      'Educación para la salud',
      'Embriología e histología',
      'Endodoncia',
      'Ética y ejercicio profesional de la odontología',
      'Expo Salud',
      'Farmacología I',
      'Farmacología II',
      'Física biológica',
      'Fisiología I',
      'Fisiología II',
      'Fundamentos de las ciencias de la vida y de la tierra',
      'Fundamentos del cristianismo',
      'Inglés aplicado a las ciencias de la salud',
      'Interpretación bíblica de la historia',
      'Introducción al trabajo final de grado',
      'Investigación en odontología',
      'Materiales dentales I',
      'Materiales dentales II',
      'Microbiología, parasitología e inmunología I',
      'Microbiología, parasitología e inmunología II',
      'Movimientos religiosos contemporáneos',
      'Oclusión',
      'Odontología legal y forense',
      'Odontología preventiva',
      'Odontopediatría',
      'Optativa I. Administración en salud',
      'Optativa III: Odontología en pacientes con discapacidad',
      'Optativa II: Odontología y nutrición materno infantil',
      'Ortodoncia',
      'Periodoncia',
      'Práctica profesional y comunitaria supervisada (PPCS)',
      'Psicología aplicada a la odontología',
      'Salud Pública',
      'Salud y autocuidado profesional',
      'Semiología',
      'Técnica de operatoria dental',
      'Técnica de prótesis fija',
      'Técnica de prótesis removible parcial y completa',
    ],
  },
  {
    career: 'Administración',
    assignment: [
      'Administración de recursos informáticos I',
      'Administración de recursos informáticos II',
      'Administración financiera',
      'Algebra I',
      'Algebra II',
      'Análisis matemático I',
      'Análisis matemático II',
      'Antropología cristiana',
      'Auditoría informática',
      'Base de datos',
      'Cálculo financiero',
      'Contabilidad I',
      'Contabilidad II',
      'Cosmovisión bíblica cristiana',
      'Derecho civil',
      'Derecho constitucional y administrativo',
      'Derecho empresario',
      'Derecho societario',
      'Dinámica eclesial',
      'Dirección en comunicación',
      'Economía I',
      'Economía II',
      'Economía III',
      'Economía IV',
      'Educación para la familia',
      'Elementos de informática',
      'Estadística',
      'Evolución del pensamiento socio-económico',
      'Fundamentos del cristianismo',
      'Informática aplicada I (Planilla de cálculo)',
      'Inglés',
      'Inglés profesional',
      'Interpretación bíblica de la historia',
      'Introducción a la comunicación visual',
      'Introducción a la contabilidad I',
      'Introducción a la contabilidad II',
      'Introducción a la economía y la empresa',
      'Modelos y simulación',
      'Observaciones y práctica profesional',
      'Organización y administración escolar',
      'Presupuesto y análisis integral',
      'Principios de administración y de organización',
      'Principios de vida saludable',
      'Propaganda y publicidad',
      'Psicología organizacional- laboral I',
      'Psicología organizacional-laboral II',
      'Recursos para la comunicación',
      'Responsabilidad social y servicio',
      'Sistema de apoyo a la toma de decisiones',
      'Sistemas y procedimientos administrativos',
      'Tecnologías informáticas emergentes',
      'Teoría de la comunicación',
      'Administración de la producción y las operaciones',
      'Administración de recursos informáticos I',
      'Administración de recursos informáticos II',
      'Análisis financiero y presupuestación',
      'Análisis, planeamiento y control',
      'Antropología bíblico-cristiana',
      'Auditoría de sistemas computarizados',
      'Auditoría informática',
      'Bases de datos',
      'Cálculo financiero',
      'Ciencia y fe',
      'Comercialización internacional',
      'Competencias directivas',
      'Comportamiento humano en las organizaciones',
      'Contabilidad gerencial',
      'Contabilidad I',
      'Contabilidad II',
      'Contabilidad pública',
      'Cosmovisión bíblico-cristiana',

      'Derecho Laboral',
      'Dirección en Comunicación',
      'Economía de las organizaciones',
      'Educación para la familia',
      'Estadística aplicada',
      'Estudios organizacionales',
      'Ética y deontología profesional',
      'Evolución del pensamiento socioeconómico',
      'Finanzas corporativas',
      'Finanzas públicas',
      'Fundamentos de la Administración',
      'Fundamentos de la Contabilidad',
      'Fundamentos del cristianismo',
      'Fundamentos del Derecho aplicado a la gestión',
      'Fundamentos del pensamiento científico',
      'Gestión de costos',
      'Gestión del cambio y de la innovación',
      'Gestión de proyectos',
      'Gestión estratégica',
      'Gestión estratégica de las personas I',
      'Gestión estratégica de las personas II',
      'Herramientas informáticas para la productividad',
      'Impuestos I',
      'Inteligencia de negocios y análisis de datos',
      'Introducción a la comunicación visual',
      'Introducción a la vida universitaria',
      'Liderazgo, negociación y resolución de conflictos',
      'Logística y gestión de la cadena de suministros',
      'Macroeconomía',
      'Marketing',
      'Marketing estratégico',
      'Modelos cuantitativos y de optimización',
      'Modelos y simulaciones',
      'Movimientos religiosos contemporáneos',
      'Prácticas profesionales supervisadas',
      'Principios de vida saludable',
      'Procesos y estructuras de las organizaciones',
      'Programa de formación integral',
      'Propaganda y publicidad',
      'Psicología Organizacional-Laboral I',
      'Psicología Organizacional-Laboral II',
      'Razonamiento lógico y matemático',
      'Responsabilidad social y servicio solidario',
      'Seminario avanzado en Administración',
      'Simulación de gestión contable',
      'Sistemas de apoyo a la toma de decisiones',
      'Sistemas integrados de información',
      'Taller de comunicación',
      'Taller de emprendimiento, innovación y creatividad',
      'Tecnologías informáticas emergentes',
      'Teoría de la Comunicación',
    ],
  },
  {
    career: 'Asistente Ejecutivo',
    assignment: [
      'Antropología bíblico cristiana',
      'Base de datos y diseño Web',
      'Ceremonial y protocolo',
      'Comportamiento organizacional y mediación',
      'Correspondencia empresarial',
      'Cosmovisión bíblico cristiana',

      'Dactilografía computarizada I',
      'Dactilografía computarizada II',
      'Ética y deontología profesional',
      'Fundamentos del cristianismo',
      'Gestión profesional',
      'Informática aplicada',
      'Inglés I',
      'Inglés II',
      'Inglés III',
      'Inglés IV',
      'Introducción a la comunicación',
      'Introducción a las relaciones públicas',
      'Liderazgo y trabajo en equipo',
      'Marketing',
      'Matemática y elementos de estadística',
      'Planilla de cálculo',
      'Práctica e informe final de Asistente Ejecutivo',
      'Práctica profesional integrada',
      'Principios contables',
      'Principios de administración y organización',
      'Principios de vida saludable',
      'Procesador de texto',
      'Programas utilitarios de oficina',
      'Psicología general',
      'Publicidad y promoción',
      'Relaciones públicas',
      'Taller de diseño gráfico',
      'Taller de redacción I',
      'Taller de redacción II',
    ],
  },
  {
    career: 'Contador Público',
    assignment: [
      'Algebra I',
      'Algebra II',
      'Análisis matemático I',
      'Análisis matemático II',
      'Antropología cristiana',
      'Cálculo financiero',
      'Contabilidad I',
      'Contabilidad II',
      'Contabilidad III',
      'Contabilidad IV',
      'Cosmovisión bíblica cristiana',
      'Derecho civil',
      'Derecho comercial',
      'Derecho constitucional y administrativo',
      'Derecho societario',
      'Economía I',
      'Economía II',
      'Economía III',
      'Economía IV',
      'Educación para la familia',
      'Elementos de informática',
      'Estadística',
      'Evolución del pensamiento socio-económico',
      'Fundamentos del cristianismo',
      'Informática aplicada',
      'Inglés',
      'Inglés profesional',
      'Interpretación bíblica de la historia',
      'Introducción a la contabilidad I',
      'Introducción a la contabilidad II',
      'Introducción a la economía y la empresa',
      'Observaciones y práctica profesional',
      'Principios de administración y organización',
      'Principios de vida saludable',
      'Recursos para la comunicación',
      'Sistemas y procedimientos administrativos',
      'Administración de recursos humanos',
      'Administración financiera',
      'Algebra I',
      'Algebra II',
      'Análisis matemático I',
      'Análisis matemático II',
      'Antropología bíbico cristiana',
      'Auditoría de sistemas computadorizados',
      'Auditoría I',
      'Auditoría II',
      'Cálculo financiero',
      'Ciencia y Fe',
      'Comercialización internacional',
      'Concursos y quiebras',
      'Contabilidad agropecuaria',
      'Contabilidad de costos',
      'Contabilidad I',
      'Contabilidad II',
      'Contabilidad III',
      'Contabilidad IV',
      'Contabilidad pública',
      'Cosmovisión bíblico cristiana',

      'Derecho civil',
      'Derecho comercial',
      'Derecho constitucional y administrativo',
      'Derecho laboral y seguridad social',
      'Derecho societario',
      'Economía I',
      'Economía II',
      'Economía III',
      'Economía IV',
      'Educación para la familia',
      'Estadística',
      'Etica y deontología profesional',
      'Evolución del pensamiento socioeconómico',
      'Finanzas públicas',
      'Formulación y evaluación de proyectos',
      'Fundamentos del cristianismo',
      'Impuestos I',
      'Impuestos II',
      'Informática aplicada',
      'Interpretación bíblica de la historia',
      'Introducción a la contabilidad I',
      'Introducción a la contabilidad II',
      'Metodología del trabajo científico',
      'Prácticas profesionales supervisadas',
      'Principios de administración y organización',
      'Principios de vida saludable',
      'Programa de formación integral',
      'Responsabilidad social y servicio solidario',
      'Simulación de gestión contable',
      'Sistemas y procedimientos administrativos',
      'Taller de integración contable I',
      'Taller de integración contable II',
      'Taller de práctica impositiva',
    ],
  },
  {
    career: 'Sistemas de  Información',
    assignment: [
      'Álgebra I',
      'Álgebra II',
      'Algoritmos y estructura de datos',
      'Análisis matemático I',
      'Análisis matemático II',
      'Antropología bíblico cristiana',
      'Arquitectura y organización de computadoras',
      'Bases de datos',
      'Comunicación oral y escrita',
      'Cosmovisión bíblico cristiana',

      'Educación para la familia',
      'Electricidad y electrónica',
      'Ética y deontología profesional',
      'Fundamentos del cristianismo',
      'Informática aplicada',
      'Ingeniería del software I',
      'Ingeniería del software II',
      'Inglés I',
      'Inglés II',
      'Interpretación bíblica de la historia',
      'Introducción a la informática',
      'Introducción a la programación',
      'Matemática discreta',
      'Principios de administración y organización',
      'Principios de vida saludable',
      'Programación I',
      'Programación II',
      'Programación III',
      'Programación IV',
      'Redes y telecomunicaciones I',
      'Sistemas de información',
      'Sistemas operativos I',
      'Teoría de la computación',

      'Administración de bases de datos',
      'Administración de recursos informáticos I',
      'Administración de recursos informáticos II',
      'Administración financiera y económica',
      'Álgebra I',
      'Álgebra II',
      'Algoritmos y estructura de datos',
      'Análisis matemático I',
      'Análisis matemático II',
      'Antropología bíblico cristiana',
      'Arquitectura y organización de computadoras',
      'Auditoría informática',
      'Bases de datos',
      'Cálculo numérico',
      'Ciencia y fe',
      'Comunicación oral y escrita',
      'Cosmovisión bíblico cristiana',

      'Derecho informático',
      'Educación para la familia',
      'Electricidad y electrónica',
      'Estadística',
      'Ética y deontología profesional',
      'Filosofía de la educación cristiana',
      'Física I',
      'Física II',
      'Física III',
      'Física IV',
      'Fundamentos del cristianismo',
      'Historia del cristianismo',
      'Informática aplicada',
      'Ingeniería del software I',
      'Ingeniería del software II',
      'Ingeniería del software III',
      'Inglés I',
      'Inglés II',
      'Inteligencia artificial',
      'Interpretación bíblica de la historia',
      'Introducción a la informática',
      'Introducción a la programación',
      'Liderazgo y negociación',
      'Matemática discreta',
      'Matemática superior',
      'Metodología del trabajo científico',
      'Modelos y simulaciones',
      'Movimientos religiosos contemporáneos',
      'Práctica supervisada',
      'Principios de administración y organización',
      'Principios de vida saludable',
      'Programación I',
      'Programación II',
      'Programación III',
      'Programación IV',
      'Proyecto',
      'Psicosociología de las organizaciones',
      'Química',
      'Redes y telecomunicaciones I',
      'Redes y telecomunicaciones II',
      'Redes y telecomunicaciones III',
      'Robótica y domótica',
      'Sistemas de apoyo a la toma de decisiones',
      'Sistemas de información',
      'Sistemas de representación',
      'Sistemas de tiempo real',
      'Sistemas operativos I',
      'Sistemas operativos II',
      'Tecnologías informáticas emergentes',
      'Teoría de la computación',

      'Administración de bases de datos',
      'Administración de sistemas de información I',
      'Administración de sistemas de Información II',
      'Administración financiera y económica',
      'Algebra y geometría analítica',
      'Análisis matemático I',
      'Análisis matemático II',
      'Antropología bíblico cristiana',
      'Arquitectura de computadoras',
      'Auditoría informática',
      'Bases de datos',
      'Cálculo numérico',
      'Ciencia y fe',
      'Comunicación oral y escrita',
      'Cosmovisión bíblica cristiana',
      'Derecho informático',
      'Educación para la familia',
      'Electricidad y electrónica',
      'Estadística',
      'Etica y deontología profesional',
      'Filosofía de la educación cristiana',
      'Fundamentos del cristianismo',
      'Informática aplicada',
      'Ingeniería del software I',
      'Ingeniería del software II',
      'Ingeniería del Software III',
      'Inglés I',
      'Inglés II',
      'Inteligencia artificial',
      'Interpretación bíblica de la historia',
      'Introducción a la informática',
      'Introducción a la ingeniería del software',
      'Introducción a la programación',
      'Lógica y algebra',
      'Matemática discreta',
      'Metodología del trabajo científico',
      'Modelos y simulaciones',
      'Negocios en entornos informáticos',
      'Práctica profesional',
      'Principios de administración y organización',
      'Principios de vida saludable',
      'Programación de dispositivos móviles',
      'Programación I',
      'Programación II',
      'Programación III',
      'Programación IV',
      'Programación V',
      'Proyecto',
      'Redes y telecomunicaciones I',
      'Redes y telecomunicaciones II',
      'Redes y Telecomunicaciones III',
      'Robótica',
      'Sistemas de apoyo a la toma de decisiones',
      'Sistemas de tiempo real',
      'Sistemas operativos',
      'Sistemas operativos II',
      'Taller complementario de arquitectura de computadoras',
      'Taller complementario de base de datos',
      'Taller complementario de electricidad y electrónica',
      'Taller complementario de tecnologías informáticas emergentes',
      'Teoría de la computación I',
      'Teoría de la computación II',
      'Tesina',
    ],
  },
  {
    career: 'Ciencias de la Educación',
    assignment: [
      'Análisis y organización de las instituciones educativas de la Educación Secundaria y Superior',
      'Análisis y reflexión de la práctica educativa',
      'Antropología bíblico-cristiana',
      'Asesoría pedagógica y orientación escolar',
      'Aspectos psicosociales y salud en el ciclo vital',
      'Ciencia y fe',
      'Corporeidad, juegos y lenguajes artísticos',
      'Corrientes pedagógicas contemporáneas',
      'Cosmovisión bíblico-cristiana',
      'Derechos humanos: ética y ciudadanía',
      'Didáctica de la Educación Inicial y Primaria',
      'Didáctica de la educación religiosa',
      'Didáctica de la educación secundaria y superior',
      'Didáctica y fundamentos del currículum',
      'Diseño curricular',
      'Economía y financiamiento de las instituciones educativas',
      'Educación emocional',
      'Educación en diferentes contextos',
      'Educación sexual integral',
      'Educación temprana',
      'Enfoques didácticos contemporáneos',
      'Filosofía de la educación',
      'Filosofía de la educación cristiana',
      'Fundamentos del cristianismo',
      'Gestión del ambiente del aprendizaje',
      'Historia de la educación argentina',
      'Historia social latinoamericana',
      'Interpretación bíblica de la historia',
      'Introducción a la filosofía',
      'Introducción a la tecnología en la educación',
      'Juegos y producción de materiales',
      'Lenguajes artísticos',
      'Liderazgo y trabajo en equipo',
      'Neurociencias y aprendizaje',
      'Observaciones en la Educación Inicial y Primaria',
      'Observaciones y prácticas en la Educación Secundaria y Superior',
      'Pedagogía',
      'Política y legislación educacional I',
      'Política y legislación educacional II',
      'Posicionamientos epistemológicos en educación',
      'Problemáticas contemporáneas en educación',
      'Procesos de evaluación de la calidad educativa',
      'Psicología del desarrollo I',
      'Psicología del desarrollo II',
      'Psicología del desarrollo III',
      'Psicología educacional I',
      'Psicología educacional II',
      'Residencia I',
      'Residencia II',
      'Responsabilidad social y servicio solidario',
      'Salud y autocuidado profesional',
      'Seminario de identidad y ética docente',
      'Seminario de investigación en problemáticas de la educación',
      'Sociología de la educación',
      'Taller de alfabetización académica',
      'Taller de comunicación oral y escrita',
      'Taller de evaluación',
      'Taller de proyectos educativos',
      'Tecnología aplicada a la educación',
    ],
  },
  {
    career: 'Comunicación',
    assignment: [
      'Análisis de la narrativa visual',
      'Análisis del discurso',
      'Animación digital',
      'Antropología',
      'Aspectos psicosociales y salud en el ciclo vital',
      'Ciencia y fe',
      'Comprensión lectora en inglés',
      'Comunicación escrita I',
      'Comunicación escrita II',
      'Comunicación y religión',
      'Consultoría en dirección de comunicación',
      'Cosmovisión bíblico cristiana',

      'Cultura, comunicación y educación',
      'Dirección en comunicación',
      'Dirección estratégica',
      'Emprendimiento',
      'Entornos digitales I',
      'Entornos digitales II',
      'Etica y deontología profesional',
      'Fundamentos del cristianismo',
      'Historia de los medios de comunicación',
      'Historia latinoamericana',
      'Historia universal de las ideas I',
      'Historia universal de las ideas II',
      'Identidad visual corporativa',
      'Interpretación bíblica de la historia',
      'Introducción a la comunicación visual',
      'Introducción al laboratorio digital',
      'Laboratorio de creatividad e innovación',
      'Laboratorio de posproducción',
      'Legislación en comunicación',
      'Liderazgo y negociación',
      'Lingüística',
      'Locución I',
      'Locución II',
      'Marketing',
      'Medios de comunicación y opinión pública',
      'Metodología de la investigación aplicada a la comunicación',
      'Movimientos religiosos contemporáneos',
      'Portafolio digital profesional',
      'Práctica profesional',
      'Principios de organización y administración',
      'Producción audiovisual I',
      'Producción audiovisual II',
      'Producción documental',
      'Propaganda y publicidad',
      'Proyecto de comunicación en las organizaciones I',
      'Proyecto de comunicación en las organizaciones II',
      'Psicología de la comunicación',
      'Psicosociología de las organizaciones',
      'Responsabilidad social',
      'Salud y autocuidado profesional',
      'Semiótica',
      'Sociología de la comunicación',
      'Taller de diseño gráfico',
      'Taller de fotografía',
      'Taller de redacción',
      'Taller integral de radio I',
      'Taller integral de radio II',
      'Teoría de la comunicación',
      'Trabajo final integrador',
    ],
  },
  {
    career: 'Comunicación Social',
    assignment: [
      'Análisis del discurso',
      'Antropología cristiana',
      'Ceremonial y protocolo',
      'Ciencia y fe',
      'Comunicación escrita I',
      'Comunicación escrita II',
      'Comunicación estratégica',
      'Comunicación institucional',
      'Comunicación radial I',
      'Comunicación radial II',
      'Comunicación televisiva I',
      'Comunicación televisiva II',
      'Cosmovisión bíblica cristiana',
      'Diagramación y reprografía I',
      'Diagramación y reprografía II',
      'Economía política',
      'Educación para la familia',
      'Elementos de informática',
      'Estadística aplicada',
      'Etica y deontología',
      'Expresión oral y locución',
      'Fonética inglesa',
      'Formación y evaluación de proyectos comunicacionales',
      'Fundamentos del cristianismo',
      'Historia argentina y americana',
      'Historia de las ideas I',
      'Historia de las ideas II',
      'Historia de los medios de comunicación',
      'Informática aplicada a la comunicación social I',
      'Informática aplicada a la comunicación social II',
      'Inglés I',
      'Inglés II',
      'Interpretación bíblica de la historia',
      'Introducción a la filosofía',
      'Introducción a la investigación',
      'Introducción a la psicología',
      'Legislación en comunicación',
      'Lingüística',
      'Literatura universal',
      'Marketing',
      'Medios de comunicación y opinión pública',
      'Pasantía',
      'Práctica periodística I',
      'Práctica periodística II',
      'Principios de vida saludable',
      'Problemática social, política y económica contemporánea',
      'Propaganda y publicidad I',
      'Propaganda y publicidad II',
      'Psicología de la comunicación',
      'Psicología social',
      'Relaciones públicas',
      'Semiótica',
      'Sociología',
      'Sociología de la comunicación',
      'Taller de redacción I',
      'Taller de redacción II',
      'Teoría de la comunicación',
    ],
  },
  {
    career: 'Inglés',
    assignment: [
      'Análisis del discurso',
      'Antropología cristiana',
      'Antropología cultural',
      'Ciencia y fe',
      'Cosmovisión bíblica cristiana',

      'Didáctica especial y observación I',
      'Didáctica especial y observación II',
      'Educación para la familia',
      'Enseñanza-aprendizaje I',
      'Enseñanza-aprendizaje II',
      'Estadística aplicada',
      'Etica y deontología profesional',
      'Filosofía de la educación cristiana',
      'Fonética inglesa I',
      'Fonética inglesa II',
      'Fonética inglesa III',
      'Fonética inglesa IV',
      'Fonética y dicción',
      'Fundamentos del cristianismo',
      'Gramática inglesa I',
      'Gramática inglesa II',
      'Gramática inglesa III',
      'Gramática inglesa IV',
      'Historia de la civilización inglesa I',
      'Historia de la civilización inglesa II',
      'Historia norteamericana',
      'Interpretación bíblica de la historia',
      'Lengua inglesa I',
      'Lengua inglesa II',
      'Lengua inglesa III',
      'Lengua inglesa IV',
      'Lengua inglesa IX',
      'Lengua inglesa V',
      'Lengua inglesa VI',
      'Lengua inglesa VII',
      'Lengua inglesa VIII',
      'Lengua inglesa X',
      'Literatura inglesa I',
      'Literatura inglesa II',
      'Literatura norteamericana',
      'Metodología del trabajo científico',
      'Principios de vida saludable',
      'Procesamiento electrónico de datos',
      'Proceso pedagógico I',
      'Proceso pedagógico II',
      'Psicología del aprendizaje',
      'Psicología evolutiva de la niñez y adolescencia',
      'Residencia pedagógica I',
      'Residencia pedagógica II',
      'Seminario de investigación en inglés I',
      'Seminario de investigación en inglés II',
      'Análisis del discurso',
      'Antropología cristiana',
      'Antropología cultural',
      'Ciencia y fe',
      'Cosmovisión bíblica cristiana',

      'Derecho civil',
      'Derecho comercial',
      'Derecho laboral',
      'Derecho procesal y penal',
      'Educación para la familia',
      'Estadística aplicada',
      'Estructuras comparadas',
      'Etica y deontología profesional',
      'Filosofía de la educación cristiana',
      'Fonética inglesa I',
      'Fonética inglesa II',
      'Fonética inglesa III',
      'Fonética inglesa IV',
      'Fonética y dicción',
      'Fundamentos del cristianismo',
      'Gramática inglesa I',
      'Gramática inglesa II',
      'Gramática inglesa III',
      'Gramática inglesa IV',
      'Gramática inglesa V',
      'Gramática inglesa VI',
      'Historia de la civilización inglesa I',
      'Historia de la civilización inglesa II',
      'Instituciones del derecho',
      'Interpretación bíblica de la historia',
      'Lengua castellana I',
      'Lengua castellana II',
      'Lengua inglesa I',
      'Lengua inglesa II',
      'Lengua inglesa III',
      'Lengua inglesa IV',
      'Lengua inglesa IX',
      'Lengua inglesa V',
      'Lengua inglesa VI',
      'Lengua inglesa VII',
      'Lengua inglesa VIII',
      'Lengua inglesa X',
      'Literatura inglesa I',
      'Literatura inglesa II',
      'Metodología del trabajo científico',
      'Principios de vida saludable',
      'Procesamiento electrónico de datos',
      'Seminario de actualización profesional',
      'Seminario de investigación en inglés I',
      'Seminario de investigación en inglés II',
      'Traducción',
      'Traducción jurídico-económica',
      'Traducción literaria',
    ],
  },
  {
    career: 'Licenciatura en Comunicación Social - Ciclo',
    assignment: [
      'Administración de recursos humanos',
      'Comunicación científica',
      'Comunicación y cultura',
      'Filosofía de la educación',
      'Formulación y evaluación de proyectos',
      'Informática aplicada a la comunicación social II',
      'Informática aplicada a la investigación',
      'Marketing',
      'Metodología de la investigación I',
      'Metodología de la investigación II',
      'Pasantía',
      'Política internacional contemporánea',
      'Trabajo final integrador',
    ],
  },
  {
    career: 'Profesorado de Inglés',
    assignment: [
      'Antropología bíblico-cristiana',
      'Ciencia y fe',
      'Cosmovisión bíblico cristiana',

      'Didáctica del inglés I',
      'Didáctica del inglés II',
      'Didáctica general',
      'Educación para la familia',
      'Ética y deontología profesional',
      'Filosofía de la educación cristiana',
      'Fonética inglesa I',
      'Fonética inglesa II',
      'Fonética inglesa III',
      'Fonética inglesa IV',
      'Fonética inglesa V',
      'Fonética inglesa VI',
      'Fonética inglesa VII',
      'Fonética inglesa VIII',
      'Fundamentos del cristianismo',
      'Gramática inglesa I',
      'Gramática inglesa II',
      'Gramática inglesa III',
      'Gramática inglesa IV',
      'Gramática inglesa V',
      'Gramática inglesa VI',
      'Historia de la civilización inglesa I',
      'Historia de la civilización inglesa II',
      'Historia de los Estados Unidos de América',
      'Inroducción a la literatura anglosajona',
      'Interpretación bíblica de la historia',
      'Lengua española I',
      'Lengua española II',
      'Lengua inglesa I',
      'Lengua inglesa II',
      'Lengua Inglesa III',
      'Lengua inglesa IV',
      'Lengua inglesa V',
      'Lengua inglesa VI',
      'Lengua inglesa VII',
      'Lengua inglesa VIII',
      'Lingüística general',
      'Literatura anglosajona I',
      'Literatura anglosajona II',
      'Pedagogía',
      'Pedagogía de la lengua extranjera',
      'Principios de vida saludable',
      'Psicolingüística',
      'Psicología del aprendizaje',
      'Psicología del desarrollo del ciclo vital',
      'Recursos tecnológicos para profesores',
      'Residencia pedagógica I',
      'Residencia pedagógica II',
      'Sociolingüística y pragmática',
      'Taller de práctica profesional I',
      'Taller de práctica profesional II',
    ],
  },
  {
    career: 'Profesorado en Ciencias de la Educación - Ciclo',
    assignment: [
      'Asesoría pedagógica',
      'Corrientes pedagógicas contemporáneas',
      'Didáctica del nivel medio y superior',
      'Estadística',
      'Evaluación educacional',
      'Filosofía de la educación',
      'Formación espiritual I',
      'Formación espiritual II',
      'Formación espiritual III',
      'Historia de la educación',
      'Informática aplicada',
      'Informe final',
      'Introducción a la filosofía',
      'Metodología de la investigación',
      'Orientación escolar',
      'Psicología del adolescente',
      'Psicología del aprendizaje',
      'Residencia pedagógica',
      'Seminario de administración escolar',
      'Seminario taller conducción educativa',
      'Seminario taller de currículum',
      'Sociología de la educación',
    ],
  },
  {
    career: 'Profesorado en Educación Física',
    assignment: [
      'Análisis del movimiento',
      'Anatomía humana y aplicada',
      'Antropología cristiana',
      'Atletismo I',
      'Atletismo II',
      'Atletismo III',
      'Atletismo IV',
      'Básquetbol I',
      'Básquetbol II',
      'Céstobol I',
      'Céstobol II',
      'Ciencia y fe',
      'Cosmovisión bíblica cristiana',

      'Educación física especial',
      'Educación física infantil I',
      'Educación física infantil II',
      'Educación para la familia',
      'Educación para la salud',
      'Educación rítmica',
      'Educación vocal',
      'Enseñanza-aprendizaje de la educación física I',
      'Enseñanza-aprendizaje de la educación física II',
      'Enseñanza-aprendizaje I',
      'Enseñanza-aprendizaje II',
      'Etica y deontología profesional',
      'Evaluación aplicada a la educación física',
      'Filosofía de la educación',
      'Filosofía de la educación cristiana',
      'Fisiología general y aplicada',
      'Fundamentos del cristianismo',
      'Fútbol I',
      'Fútbol II',
      'Gestión de la educación física',
      'Gestión institucional',
      'Gimnasia Artística I',
      'Gimnasia artística II',
      'Gimnasia I',
      'Gimnasia II',
      'Gimnasia III',
      'Gimnasia IV',
      'Gimnasia V',
      'Gimnasia VI',
      'Hándbol I',
      'Hándbol II',
      'Hockey I',
      'Hockey II',
      'Interpretación bíblica de la historia',
      'Introducción a la educación física',
      'Metodología del trabajo científico',
      'Natación I',
      'Natación II',
      'Nutrición',
      'Práctica de la enseñanza I',
      'Práctica de la enseñanza II',
      'Práctica de la enseñanza III',
      'Principios de vida saludable',
      'Proceso pedagógico I',
      'Proceso pedagógico II',
      'Psicología evolutiva I',
      'Psicología evolutiva II',
      'Psicología evolutiva III',
      'Recreación I',
      'Recreación II',
      'Sistema educativo',
      'Sóftbol I',
      'Sóftbol II',
      'Taller didáctico',
      'Teoría de la educación física',
      'Teoría y práctica del entrenamiento I',
      'Teoría y práctica del entrenamiento II',

      'Vida en la naturaleza I',
      'Vida en la naturaleza II',
      'Vóleibol I',
      'Vóleibol II',
    ],
  },
  {
    career: 'Profesorado Universitario - PL',
    assignment: [
      'Antropología social (Niv.Plan 2015)',
      'Ciencia y Fe (Niv.Plan 2015)',
      'Cosmovisión bíblico cristiana (Niv.Plan 2015)',
      'Curriculum',
      'Didáctica del nivel medio y superior',
      'Didáctica especial y observación',
      'Educación para la familia (Niv.Plan anterior)',
      'Elementos de informática (Niv.Plan anterior)',
      'Epistemología (Niv.Plan anterior)',
      'Estadística (Niv.Plan anterior y 2015)',
      'Evaluación educacional',
      'Filosofía de la educación',
      'Formación espiritual III (Niv.Plan anterior)',
      'Formación espiritual I (Niv.Plan anterior)',
      'Fundamentos de la educación',
      'Gestión institucional',
      'Historia de la ideas I (Niv.Plan 2015)',
      'Historia de las ideas II (Niv.Plan 2015)',
      'Informática aplicada',
      'Inglés II (Niv.Plan 2015)',
      'Inglés I (Niv.Plan 2015)',
      'Introducción a la filosofía (Niv.Plan anterior y 2015)',
      'Introducción a la psicología (Niv.Plan anterior y 2015)',
      'Metodología de la investigación',
      'Orientación escolar (Niv.Plan anterior)',
      'Psicología del adolescente y juventud',
      'Psicología del aprendizaje',
      'Psicología Social (Niv.Plan 2015)',
      'Recursos audiovisuales e informáticos',
      'Residencia pedagógica',
      'Sociología (Niv.Plan 2015)',
      'Taller de redacción II (Niv.Plan 2015)',
      'Taller de redacción I (Niv.Plan 2015)',
      'Teoría de la comunicación (Niv.Plan 2015)',
      'Trabajo final integrador',
    ],
  },
  {
    career: 'Psicología',
    assignment: [
      'Acompañamiento terapéutico I',
      'Acompañamiento terapéutico II',
      'Antropología bíblico cristiana',
      'Antropología social',
      'Bases psico neuro biológicas de la conducta',
      'Corrientes fundamentales en psicoterapia',
      'Corrientes psicológicas contemporáneas',
      'Cosmovisión bíblico cristiana',

      'Epistemología de la psicología',
      'Estudios complementarios y psicofarmacología',
      'Filosofía',
      'Fundamentos del cristianismo',
      'Inglés profesional I',
      'Inglés profesional II',
      'Interpretación bíblica de la historia',
      'Neuropsicología',
      'Procesos básicos y su aplicación a la psicología I',
      'Procesos básicos y su aplicación a la psicología II',
      'Psicoeducación familiar',
      'Psicología de la adultez y vejez',
      'Psicología de la niñez y adolescencia',
      'Psicología de la personalidad',
      'Psicología profunda I',
      'Psicología profunda II',
      'Psicopatología I',
      'Psicopatología II',
      'Salud y autocuidado profesional',
      'Seminario de cultura y sociedad',
      'Taller de intervención en crisis',
      'Teorías del desarrollo y psicología de la infancia',

      'Antropología bíblico cristiana',
      'Antropología social',
      'Bases psico neuro biológicas de la conducta',
      'Ciencia y fe',
      'Corrientes fundamentales en psicoterapia',
      'Corrientes psicológicas contemporáneas',
      'Cosmovisión bíblico cristiana',
      'Criminología infanto-juvenil',

      'Diseño de investigación en psicología',
      'Epistemología de la psicología',
      'Estadística aplicada a la psicología',
      'Estudios complementarios y psicofarmacología',
      'Etica y deontología profesional',
      'Evaluación y diagnóstico psicológico',
      'Filosofía',
      'Filosofía de la educación cristiana',
      'Fundamentos del cristianismo',
      'Informática aplicada al ejercicio profesional',
      'Inglés profesional I',
      'Inglés profesional II',
      'Interpretación bíblica de la historia',
      'Introducción a la práctica profesional del psicólogo',
      'Introducción a los talleres en psicología',
      'Metodología de la investigación en psicología',
      'Neuropsicología',
      'Perspectivas sociológicas contemporáneas',
      'Práctica profesional supervisada I',
      'Práctica profesional supervisada II',
      'Procesos básicos y su aplicación a la psicología I',
      'Procesos básicos y su aplicación a la psicología II',
      'Psicoeducación familiar',
      'Psicología clínica I',
      'Psicología clínica II',
      'Psicología de la adultez y vejez',
      'Psicología de la niñez y adolescencia',
      'Psicología de la personalidad',
      'Psicología de la salud',
      'Psicología diferencial aplicada',
      'Psicología educacional I',
      'Psicología educacional II',
      'Psicología jurídico-forense I',
      'Psicología jurídico-forense II',
      'Psicología organizacional-laboral I',
      'Psicología organizacional-laboral II',
      'Psicología profunda I',
      'Psicología profunda II',
      'Psicología social y comunitaria I',
      'Psicología social y comunitaria II',
      'Psicología y espiritualidad',
      'Psicometría',
      'Psicopatología I',
      'Psicopatología II',
      'Salud y autocuidado profesional',
      'Seminario de cultura y sociedad',
      'Taller de habilidades terapéuticas',
      'Taller de intervención en crisis',
      'Taller de investigación',
      'Taller de observación y entrevista',
      'Taller de proyectos',
      'Taller de técnicas grupales',
      'Técnicas proyectivas',
      'Técnicas psicométricas',
      'Teorías del desarrollo y psicología de la infancia',
      'Trabajo final integrador I',
      'Trabajo final integrador II',

      'Antropología cultural',
      'Antropología teológica',
      'Biología',
      'Ciencia y religión',
      'Corrientes psicológicas contemporáneas',
      'Cristología y soteriología',
      'Didáctica especial y observaciones',
      'Ecoetología',
      'Enseñanza-Aprendizaje I',
      'Enseñanza-Aprendizaje II',
      'Epistemología',
      'Escatología bíblica',
      'Estadística aplicada',
      'Etica y deontología profesional',
      'Genética humana',
      'Historia del adventismo',
      'Historia de la psicología',
      'Historia del cristianismo',
      'Informática aplicada I',
      'Informática aplicada II',
      'Inglés I',
      'Inglés II',
      'Introducción a la filosofía',
      'Introducción general a la Biblia',
      'Lógica',
      'Metodología del trabajo científico',
      'Movimientos religiosos contemporáneos',
      'Neurofisiología y neuroanatomía',
      'Observación y prácticas de ensayo',
      'Organización y administración escolar',
      'Orientación escolar',
      'Política y legislación educacional',
      'Procesamiento electrónico de datos',
      'Proceso pedagógico I',
      'Proceso pedagógico II',
      'Psicodiagnóstico',
      'Psicoestadística',
      'Psicología de la personalidad',
      'Psicología del aprendizaje',
      'Psicología de la Salud',
      'Psicología diferencial',
      'Psicología evolutiva I',
      'Psicología evolutiva II',
      'Psicología evolutiva III',
      'Psicología evolutiva IV',
      'Psicología experimental',
      'Psicología forense',
      'Psicología general I',
      'Psicología general II',
      'Psicología genética I',
      'Psicología genética II',
      'Psicología institucional',
      'Psicología laboral',
      'Psicología profunda I',
      'Psicología profunda II',
      'Psicología social',
      'Psicometría I',
      'Psicometría II',
      'Psicopatología',
      'Residencia pedagógica I',
      'Residencia pedagógica II',
      'Técnicas proyectivas I',
      'Técnicas proyectivas II',
      'Teología de la educación',
      'Teología de la salud',
    ],
  },
  {
    career: 'Psicopedagogía',
    assignment: [
      'Antropología cristiana',
      'Antropología cultural',
      'Biología',
      'Ciencia y fe',
      'Cosmovisión bíblica cristiana',
      'Diagnóstico psicopedagógico I',
      'Diagnóstico psicopedagógico II',
      'Didáctica especial I',
      'Didáctica especial II',
      'Didáctica especial III',
      'Didáctica especial IV',
      'Dinámica de grupos',
      'Educación para la familia',
      'Enseñanza-aprendizaje I',
      'Enseñanza-aprendizaje II',
      'Epistemología',
      'Estadística aplicada',
      'Etica y deontología profesional',
      'Filosofía de la educación cristiana',
      'Fundamentos del cristianismo',
      'Informática aplicada a la educación I',
      'Informática aplicada a la educación II',
      'Inglés I',
      'Inglés II',
      'Interpretación bíblica de la historia',
      'Introducción a la filosofía',
      'Lógica',
      'Metodología del trabajo científico',
      'Neuroanatomía y neurofisiología',
      'Organización y administración escolar',
      'Orientación escolar',
      'Orientación vocacional y profesional',
      'Política y legislación educacional',
      'Principios de vida saludable',
      'Procesamiento electrónico de datos',
      'Proceso pedagógico I',
      'Proceso pedagógico II',
      'Psicoestadística',
      'Psicología de la comunicación',
      'Psicología de la personalidad',
      'Psicología del aprendizaje',
      'Psicología evolutiva I',
      'Psicología evolutiva II',
      'Psicología evolutiva III',
      'Psicología evolutiva IV',
      'Psicología general I',
      'Psicología general II',
      'Psicología genética I',
      'Psicología genética II',
      'Psicología institucional',
      'Psicología laboral',
      'Psicología profunda I',
      'Psicología profunda II',
      'Psicología social',
      'Psicopatología',
      'Psicopedagogía diferencial',
      'Psicopedagogía terapéutica I',
      'Psicopedagogía terapéutica II',
      'Seminario de investigación en psicopedagogía I',
      'Seminario de investigación en psicopedagogía II',
      'Sociología de la educación',
      'Técnicas de exploración psicopedagógica',
      'Tesis de licenciatura en psicopedagogía I',
      'Tesis de licenciatura en psicopedagogía II',
    ],
  },
  {
    career: 'Trabajo Social',
    assignment: [
      'Administración en servicio social',
      'Derecho social I',
      'Derecho social II',
      'Educación para la familia',
      'Estadística aplicada',
      'Etica y deontología profesional',
      'Filosofía de la educación',
      'Formación espiritual I',
      'Formación espiritual II',
      'Formación espiritual III',
      'Formación espiritual IV',
      'Historia del trabajo social',
      'Historia económica social, regional y nacional',
      'Inglés I',
      'Inglés II',
      'Introducción a la filosofía',
      'Introducción a la psicología',
      'Introducción al trabajo social I',
      'Introducción al trabajo social II',
      'Metodología de la investigación social',
      'Metodología del trabajo científico',
      'Observación y práctica del trabajo social I',
      'Observación y práctica del trabajo social II',
      'Observación y práctica del trabajo social III',
      'Políticas sociales',
      'Práctica asistente social',
      'Principios de salud',
      'Problemática Social, Política y Económica Contemporánea',
      'Procesamiento electrónico de datos',
      'Psicología del adolescente y juventud',
      'Psicología del adulto',
      'Psicología de la niñez',
      'Psicología institucional',
      'Psicología social',
      'Recursos audiovisuales e informáticos',
      'Salud mental',
      'Salud pública',
      'Seminario de investigación en trabajo social I',
      'Servicio social en educación',
      'Sistemas y servicios de salud',
      'Sociología I',
      'Sociología II',
      'Sociología III',
      'Sociología IV',
      'Trabajo social I',
      'Trabajo social II',
      'Trabajo social III',
      'Trabajo social IV',
      'Trabajo social V',
      'Administración en servicio social',
      'Antropología Cultural',
      'Ciencia y Religión',
      'Derecho social I',
      'Derecho social II',
      'Desarrollo económico social',
      'Educación para la familia',
      'Estadística aplicada',
      'Etica y deontología profesional',
      'Filosofía de la educación',
      'Formación espiritual I',
      'Formación espiritual II',
      'Formación espiritual III',
      'Formación espiritual IV',
      'Historia del trabajo social',
      'Historia económica social, regional y nacional',
      'Informática Aplicada',
      'Inglés I',
      'Inglés II',
      'Introducción a la filosofía',
      'Introducción a la psicología',
      'Introducción al trabajo social I',
      'Introducción al trabajo social II',
      'Metodología de la investigación social',
      'Metodología del trabajo científico',
      'Observación y práctica del trabajo social I',
      'Observación y práctica del trabajo social II',
      'Observación y práctica del trabajo social III',
      'Planeamiento',
      'Políticas sociales',
      'Práctica integrada',
      'Principios de salud',
      'Problemática Social, Política y Económica Contemporánea',
      'Procesamiento electrónico de datos',
      'Psicología del adolescente y juventud',
      'Psicología del adulto',
      'Psicología de la niñez',
      'Psicología institucional',
      'Psicología social',
      'Recursos audiovisuales e informáticos',
      'Residencia profesional',
      'Salud mental',
      'Salud pública',
      'Seminario de investigación en trabajo social I',
      'Seminario de Investigación II',
      'Servicio social en educación',
      'Sistemas y servicios de salud',
      'Sociología I',
      'Sociología II',
      'Sociología III',
      'Sociología IV',
      'Tercer Sector',
      'Trabajo final abarcador I',
      'Trabajo final abarcador II',
      'Trabajo social I',
      'Trabajo social II',
      'Trabajo social III',
      'Trabajo social IV',
      'Trabajo social V',
      'Trabajo Social VI',
    ],
  },
  {
    career: 'Traductorado Público de Inglés',
    assignment: [
      'Antropología bíblico-cristiana',
      'Ciencia y fe',
      'Cosmovisión bíblico cristiana',

      'Derecho civil',
      'Derecho comercial',
      'Derecho constitucional y administrativo',
      'Derecho laboral y seguridad social',
      'Derecho procesal civil y penal',
      'Educación para la familia',
      'Ética y deontología profesional',
      'Filosofía de la educación cristiana',
      'Fonética inglesa I',
      'Fonética inglesa II',
      'Fonética inglesa III',
      'Fonética inglesa IV',
      'Fonética inglesa V',
      'Fonética inglesa VI',
      'Fundamentos del cristianismo',
      'Gramática inglesa I',
      'Gramática inglesa II',
      'Gramática inglesa III',
      'Gramática inglesa IV',
      'Gramática inglesa V',
      'Historia de la civilización inglesa I',
      'Historia de la civilización inglesa II',
      'Historia de los Estados Unidos de América',
      'Interpretación bíblica de la historia',
      'Introducción a la interpretación',
      'Introducción a la literatura anglosajona',
      'Introducción al ejercicio profesional',
      'Lengua española I',
      'Lengua española II',
      'Lengua inglesa I',
      'Lengua inglesa II',
      'Lengua inglesa III',
      'Lengua inglesa IV',
      'Lengua inglesa V',
      'Lengua inglesa VI',
      'Lengua inglesa VII',
      'Lengua inglesa VIII',
      'Literatura anglosajona I',
      'Literatura anglosajona II',
      'Práctica de interpretación',
      'Práctica profesional',
      'Principios de vida saludable',
      'Recursos tecnológicos para traductores',
      'Seminario sobre nuevas especializaciones',
      'Traducción científico-técnica',
      'Traducción económico-financiera',
      'Traducción I',
      'Traducción II',
      'Traducción jurídica',
      'Traducción literaria',
    ],
  },
  {
    career: 'Instructorado Bíblico Universitario',
    assignment: [
      'Apocalipsis',
      'Arqueología e historia del antiguo cercano oriente (ACO)',
      'Castellano I (Gramática)',
      'Castellano II (Ortografía y redacción)',
      'Ciencia y religión',
      'Comunicaciones',
      'Contextualización misiológica',
      'Culto y adoración',
      'Daniel',
      'Didáctica y administración pastoral',
      'Doctrinas bíblicas',
      'Educación para la familia',
      'Elementos de informática',
      'Epístolas I',
      'Epístolas II',
      'Evangelización personal',
      'Evangelización por impresos',
      'Fuentes bíblicas',
      'Griego I',
      'Griego II',
      'Griego III',
      'Hebreo I',
      'Hebreo II',
      'Historia Bíblica I',
      'Historia Bíblica II',
      'Historia del adventismo',
      'Historia eclesiástica',
      'Homilética I',
      'Homilética II',
      'Inglés básico',
      'Inglés I',
      'Inglés II',
      'Introducción a la investigación',
      'Introducción a los evangelios',
      'Libros históricos y poéticos del Antiguo Testamento',
      'Libros proféticos del Antiguo Testamento',
      'Métodos de evangelización pública',
      'Ministerios juveniles',
      'Misión de la iglesia',
      'Monografía de investigación',
      'Música sacra',
      'Orientación profética',
      'Práctica de evangelización personal',
      'Práctica de ministerios juveniles',
      'Religiones comparadas',
      'Residencia de evangelización por impresos',
      'Residencia de evangelización pública',
      'Seminario de crecimiento de iglesia 1',
      'Seminario de crecimiento de iglesia 2',
      'Seminario de crecimiento de iglesia 3',
      'Seminario de crecimiento de iglesia 4',
      'Teología de la educación cristiana',
      'Teología de la salud',
      'Teología del Pentateuco',
      'Teología sistemática I',
      'Teología sistemática II',
    ],
  },
  {
    career: 'Teología',
    assignment: [
      'Apocalipsis',
      'Arqueología e historia del antiguo cercano oriente',
      'Castellano I (gramática)',
      'Castellano II (ortografía y redacción)',
      'Ciencia y religión',
      'Comunicaciones',
      'Contextualización misiológica',
      'Corrientes teológicas contemporáneas',
      'Crecimiento de iglesia 1',
      'Crecimiento de iglesia 2',
      'Crecimiento de iglesia 3',
      'Crecimiento de iglesia 4',
      'Crecimiento de iglesia 5',
      'Crecimiento de iglesia 6',
      'Crecimiento de iglesia 7',
      'Crecimiento de iglesia 8',
      'Culto y adoración',

      'Daniel',
      'Didáctica y administración pastoral',
      'Dinámica eclesial',
      'Doctrinas bíblicas',
      'Educación para la familia',
      'Elementos de informática',
      'Epístolas I',
      'Epístolas II',
      'Estadística aplicada',
      'Etica cristiana',
      'Evangelización personal',
      'Evangelización por impresos',
      'Examen integrador',
      'Fuentes bíblicas',
      'Griego I',
      'Griego II',
      'Griego III',
      'Hebreo I',
      'Hebreo II',
      'Historia Bíblica I',
      'Historia Bíblica II',
      'Historia del adventismo',
      'Historia eclesiástica',
      'Homilética I',
      'Homilética II',
      'Inglés básico',
      'Inglés I',
      'Inglés II',
      'Introducción a la investigación',
      'Introducción a los evangelios',
      'Investigación guiada I',
      'Investigación guiada II',
      'Libros históricos y poéticos del Antiguo Testamento',
      'Libros proféticos del Antiguo Testamento',
      'Métodos de evangelización pública',
      'Ministerios juveniles',
      'Misión de la iglesia',
      'Monografía de investigación',
      'Música sacra',
      'Orientación profética',
      'Práctica de didáctica y administración pastoral',
      'Práctica de evangelización personal',
      'Práctica de ministerios juveniles',
      'Psicología pastoral',
      'Religiones comparadas',
      'Residencia de evangelización por impresos',
      'Residencia de evangelización pública',
      'Residencia misionera',
      'Residencia pastoral',
      'Teología de la educación cristiana',
      'Teología de la salud',
      'Teología del pentateuco',
      'Teología sistemática I',
      'Teología sistemática II',
      'Tesis',
    ],
  },
  {
    career: 'Preuniversitario',
    assignment: [
      'Biología I',
      'Biología II',
      'Ciencia y fe',
      'Cosmovisión bíblico cistiana',
      'Español I',
      'Español II',
      'Física I',
      'Física II',
      'Historia de la medicina',
      'Inglés I',
      'Inglés II',
      'Introducción a la educación virtual',
      'Química I',
      'Química II',

      'Ciencia y fe',
      'Comunicaciones',
      'Cosmovisión bíblico cristiana',
      'Elementos de informática',
      'Español I',
      'Español II',
      'Evangelismo por impresos',
      'Historia del adventismo',
      'Inglés I',
      'Inglés II',
      'Introducción a la educación virtual',
      'Introducción a los evangelios',
      'Ministerios juveniles',
      'Misión de la iglesia',
      'Música Sacra',
      'Práctica de ministerios juveniles',
    ],
  },
]

function getCollection(collection, db = process.env.DATABASE_NAME) {
  return client.db(db).collection(collection)
}

export default async function main() {
  try {
    await client.connect().then(async () => {
      console.log('Connected successfully to server || CareersInsert')

      const careers_collection = getCollection('Career')
      const courses_collection = getCollection('Course')

      await careers_collection.deleteMany({})
      await courses_collection.deleteMany({})

      for (const career of careers_and_courses) {
        try {
          const inserted_career = async () => {
            const career_insert = await careers_collection.insertOne({
              name: career.career,
              active: true,
              academicUnitId: null,
            })

            const courses_to_insert = career.assignment.map((c) => {
              return {
                name: c,
                careerId: new ObjectId(career_insert.insertedId),
                active: true,
              }
            })

            const courses_insert =
              await courses_collection.insertMany(courses_to_insert)
          }

          await inserted_career()
        } catch (e) {
          console.log('Error occured while inserting career', e)
        }
      }
    })
  } catch (error) {
    console.error(
      'An error occurred while inserting careers and courses:',
      error
    )
  } finally {
    await client.close()
    console.log('Connection closed || CareersInsert')
  }
}

main().catch(console.error)
