name: Deploy to testvidonline
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf uap-vid
            git clone https://github.com/bojkomatias/uap-vid.git
            cd uap-vid
            git checkout origin/develop
            cp /home/nodo/apps/enviroments/uap-vid.env ./.env
            docker build -t uap:latest .
            docker-compose up -d --no-deps --force-recreate uap-research
