name: UAP Deploy
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./server/
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 7
                  run_install: false

            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'
            - name: Install dependencies
              run: rm -rf node_modules && pnpm i --frozen-lockfile --no-verify-store-integrity
            - name: Lint
              run: pnpm lint
    build:
        needs: [lint]
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./server/
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 7
                  run_install: false

            - name: Use Node.js $16
              uses: actions/setup-node@v3
              with:
                  node-version: $16
                  cache: 'pnpm'

            - name: Install dependencies
              run: rm -rf node_modules && pnpm i --frozen-lockfile --no-verify-store-integrity

            - name: Prisma generate
              run: npx prisma generate

            - name: Build
              run: pnpm build
    deploy:
        needs: [lint, build]
        runs-on: ubuntu-latest
        steps:
            # Deploy to uap by ssh
            - name: Install SSH Client
              run: sudo apt-get install -y sshpass

            - name: Deploy via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      sshpass -p ${{ secrets.SSH_PASSWORD }} 
                      ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 

                      # Delete old code
                      rm -rf uap-vid

                      # clone latest code
                      git clone https://github.com/bojkomatias/uap-vid.git

                      # go to uap-vid folder
                      cd uap-vid

                      # build docker image
                      docker build -t uap:latest .

                      # docker compose down
                      docker-compose down

                      # docker compose up with name uap 
                      docker-compose up -d --name uap
